### ISSUE TITLE
Add Custom Status Code For Long-Running Scripts

### ISSUE THREAD

**Issue by jmwright** [occi-cad/occi-server#10]
Currently, when a script takes too long to complete, the API will return a URL for the client to poll to see when the execution is finished. The HTTP status code returned is 200, just as it is with a STEP/STL download. If the API returned a different status code, something like 206 or 307, it would be easier for the client to process the incoming data. Right now the client has to peek inside the data to see if it's an incoming STEP/STL file, or JSON data.

**Comment by jmwright** [comment]
In the original description of this feature there was going to be a job URL that the client could periodically check.

https://occi.archiyou.nl/slowtest/eABxxxxxxxxxxAN/job/230cb4da-xxxx-xxxx-xxxx-3caxxxxxxxxa

How is the client given this URL? I get JSON back when the execution times out, and I see a `celery_task_id`, but I'm not sure how to construct/retrieve the URL that can be used to check the status of the job.

**Comment by mvdnet** [comment]
There is a redirect header being added that contains the job URL 
The browser follows this automatically, but I guess Python does not.
Are you using requests?

**Comment by jmwright** [comment]
Thanks. I'll have to figure out how to get Python's request module to handle redirects.

**Comment by mvdnet** [comment]
Something like this:
```
r = requests.get('http://github.com/', allow_redirects=False)
r.headers['Location']  # https://github.com/ -- the redirect destination
```

**Comment by jmwright** [comment]
I'm getting a 307 for the job redirect, but that makes sense because a job is temporary until the model is complete and cached.

**Comment by jmwright** [comment]
The FreeCAD plugin commit [here](https://github.com/occi-cad/occi-freecad-plugin/tree/c79c2ccca8b058bbe5b76b01504998883fde8613) adds  handling for the custom 202 status code, and so we now have support for long running model scripts on the client side.
