### ISSUE TITLE
Add an Option Data Type

### ISSUE THREAD

**Issue by jmwright** [occi-cad/occi-server#13]
Presets can fill this role (sort of), but to avoid having to scroll through a large number of preset buttons in the plugin, it might be useful to have an option type, probably represented as a drop-down in the FreeCAD plugin. If the user has only a set number of options to chose from, that would be a good use case for the Option data type. I have two specific use cases listed below.

**Use Case 1**: When generating a metric screw, not all lengths are manufactured, and mostly come in multiples of 2. An option could be added to a model that is something like `[6, 8, 10, 12, 16, 20]` to cover common lengths.

 **Use Case 2**: There are common screw head types, and these are difficult to have a user enter as text or a number. Examples of screw head types can be seen [here](https://cq-warehouse.readthedocs.io/en/latest/fastener.html). For ease of use, rather than using the ISO numbers, the common names should probably be used in the option instead: `[ButtonHeadScrew, CounterSunkScrew, SetScrew...]`

**Comment by mvdnet** [comment]
Implemented:
Data model  ParamConfigOptions: { type: 'options', options:  [ 'FreeCad','Cadquery']  } in Param.py
With appropriate checks applied in ApiGenerator. 
For config example see: scriptlibrary/textoptions

Commit: 76899fc0854ba0f3a22fb03c15a147ab2619e98a
