### ISSUE TITLE
Search Seems to Match Models It Should Not

### ISSUE THREAD

**Issue by jmwright** [occi-cad/occi-server#17]
Since the last update with the fuzzy search, it seems like the search matches are too broad. This...

https://occi.archiyou.nl/search?q=box

...does not yield just the box model, but `slowtest`, `text` and `bracket` as well.

**Comment by mvdnet** [comment]
@jmwright  Should now be less 'fuzzy'. Had a distance of 2.  Now 1.
It searches everything, so for short query strings it can hit something very quickly!
Let's try with these settings. Reopen issue when counter intuitive results pop up.
