### ISSUE TITLE
Text Example Returns STEP Inside JSON Data

### ISSUE THREAD

**Issue by jmwright** [occi-cad/occi-server#18]
I was getting a STEP parsing error in FreeCAD and so I tried to access the data directly. This is what I see.

![Screenshot from 2023-02-09 09-50-09](https://user-images.githubusercontent.com/1015439/217846860-8244c769-6d5f-4ea9-ad0a-58ef209744ab.png)

It seems to be spinning the work off into a job and I am getting what looks like the job-finished data, but the plugin does not seem to get a 202 status code. The plugin ends up writing all of the data (JSON and STEP) to the temporary file because it gets a 200, but then FreeCAD can't import it because it's not a valid STEP file. This is the first non-slowtest model where I have it time out and I also have had to read the data from the API in chunks.

Here is the URL I used to request the text.

https://occi.archiyou.nl/tests/text/?text=cadquery

**Comment by mvdnet** [comment]
Hotfix 2f00bce1233e9bed528a0e62d80bcb74653b4b51
Small bug in cleaning compute file directory for non-cachable scripts
