### ISSUE TITLE
Include cq_warehouse in Docker Image

### ISSUE THREAD

**Issue by jmwright** [occi-cad/occi-server#19]
I have a rudimentary screw generator working in a local server, but it requires [cq_warehouse](https://github.com/gumyr/cq_warehouse). In order to install this, I added the following line(s) to the Dockerfile:
```
# Install Git so that we can install cq_warehouse from GitHub
RUN apt-get update; apt-get install -y git
```
And then added this line to the bottom of requirements.txt:
```
git+https://github.com/gumyr/cq_warehouse.git#egg=cq_warehouse
```
I think cq_warehouse would be a useful CadQuery community extension to include by default. I also think it would be a nice demo to show people that they can get multiple sizes of nuts and screws quickly. This also ties into the Option data type, so that we can limit the options on things like fastener head type.

**Comment by mvdnet** [comment]
Done. 
Also added test model in scriptlibrary: /cqwarehouse/nut
